

site_name: Opencast - Users Guide
repo_url: https://bitbucket.org/opencast-community/matterhorn/src/develop/docs/guides/user/docs

# Default theme used is readthedocs
theme: readthedocs

# The directory that contain the source .md files
docs_dir: 'docs'

# The directory to which the site is built using mkdocs
site_dir: 'site'

# This needs to be listed in order to populate the left navigation and the TOC
# Items will appear in this order

pages:
- ['index.md', 'Introduction']
- ['login.md', 'Log-in']
- ['events.md', 'Events']
- ['series.md', 'Series']
- ['systems.md', 'Systems']
- ['users.md', 'Users']
- ['groups.md', 'Groups']
- ['accesspolicies.md', 'Access Policies']
- ['themes.md', 'Themes']
- ['processing.md', 'Processing']
- ['videoeditor.md', 'Video Editor']
- ['searchandfilter.md', 'Search & Filter']
- ['configure.md', 'Configure the UI']
- ['glossary.md', 'Glossary']
- ['i18n.md', 'Internationalization']
